"""updates to models

Revision ID: 2ef331c3c68a
Revises: 
Create Date: 2022-05-11 16:49:43.824388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef331c3c68a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ability_image', sa.String(), nullable=False),
    sa.Column('uses_resource', sa.Boolean(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_cost', sa.Integer(), nullable=True),
    sa.Column('uses_charges', sa.Boolean(), nullable=False),
    sa.Column('num_charges', sa.Integer(), nullable=True),
    sa.Column('charge_recharge_rate', sa.Integer(), nullable=True),
    sa.Column('uses_cooldown', sa.Boolean(), nullable=False),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('channeled', sa.Boolean(), nullable=False),
    sa.Column('channel_time', sa.Float(precision=1), nullable=True),
    sa.Column('ultimate', sa.Boolean(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('intro', sa.String(length=500), nullable=False),
    sa.Column('hero_image', sa.String(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('resource', sa.Boolean(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_amount', sa.Integer(), nullable=True),
    sa.Column('physical_armor', sa.Integer(), nullable=False),
    sa.Column('magic_resist', sa.Integer(), nullable=False),
    sa.Column('attack_damage', sa.Integer(), nullable=False),
    sa.Column('attack_range', sa.Integer(), nullable=False),
    sa.Column('attack_speed', sa.Float(precision=1), nullable=False),
    sa.Column('move_speed', sa.Float(precision=1), nullable=False),
    sa.Column('num_of_abilities', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_abilities',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heros.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_abilities')
    op.drop_table('heros')
    op.drop_table('abilities')
    op.drop_table('users')
    # ### end Alembic commands ###
