"""initial models

Revision ID: 0ea4fd8d9ebe
Revises: ffdc0a98111c
Create Date: 2022-05-10 22:53:42.429990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea4fd8d9ebe'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ability_image', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_cost', sa.Integer(), nullable=True),
    sa.Column('num_charges', sa.Integer(), nullable=True),
    sa.Column('charge_recharge_rate', sa.Integer(), nullable=True),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('channel_time', sa.Float(precision=1), nullable=True),
    sa.Column('ultimate', sa.Boolean(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('intro', sa.String(length=500), nullable=False),
    sa.Column('hero_image', sa.String(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('resource', sa.Boolean(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_amount', sa.Integer(), nullable=True),
    sa.Column('physical_armor', sa.Integer(), nullable=False),
    sa.Column('magic_resist', sa.Integer(), nullable=False),
    sa.Column('attack_damage', sa.Integer(), nullable=False),
    sa.Column('attack_range', sa.Integer(), nullable=False),
    sa.Column('attack_speed', sa.Float(precision=1), nullable=False),
    sa.Column('move_speed', sa.Float(precision=1), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_abilities',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heros.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_abilities')
    op.drop_table('heros')
    op.drop_table('abilities')
    # ### end Alembic commands ###
