"""empty message

Revision ID: 55b16913c534
Revises: 
Create Date: 2022-05-18 16:38:29.839205

"""
import os
environment = os.getenv("FLASK_ENV")
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b16913c534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ability_image', sa.String(), nullable=False),
    sa.Column('uses_resource', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_cost', sa.Integer(), nullable=True),
    sa.Column('uses_charges', sa.Integer(), nullable=False),
    sa.Column('num_charges', sa.Integer(), nullable=True),
    sa.Column('charge_recharge_rate', sa.Integer(), nullable=True),
    sa.Column('uses_cooldown', sa.Integer(), nullable=False),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('channeled', sa.Integer(), nullable=False),
    sa.Column('channel_time', sa.Float(precision=1), nullable=True),
    sa.Column('ultimate', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('intro', sa.String(length=500), nullable=False),
    sa.Column('hero_image', sa.String(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('resource', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=20), nullable=True),
    sa.Column('resource_amount', sa.Integer(), nullable=True),
    sa.Column('physical_armor', sa.Integer(), nullable=False),
    sa.Column('magic_resist', sa.Integer(), nullable=False),
    sa.Column('attack_damage', sa.Integer(), nullable=False),
    sa.Column('attack_range', sa.Integer(), nullable=False),
    sa.Column('attack_speed', sa.Float(precision=1), nullable=False),
    sa.Column('move_speed', sa.Float(precision=1), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_abilities',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heros.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'ability_id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute('ALTER TABLE users SET SCHEMA hero_builder_schema;')
        op.execute('ALTER TABLE abibities SET SCHEMA hero_builder_schema;')
        op.execute('ALTER TABLE heros SET SCHEMA hero_builder_schema;')
        op.execute('ALTER TABLE hero_abilities SET SCHEMA hero_builder_schema;')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_abilities')
    op.drop_table('heros')
    op.drop_table('abilities')
    op.drop_table('users')
    # ### end Alembic commands ###
