"""updates to user icon

Revision ID: 680a04e0ba2e
Revises: 9140d91d24e7
Create Date: 2023-01-24 14:55:29.285395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680a04e0ba2e'
down_revision = '9140d91d24e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
